language: php
branches:
  only:
    - master
sudo: required
services:
  - docker
before_install:
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
script:
  - make push-latest push-version
notifications:
  email:
    - 120011676@qq.com