version: '3'
services:
  resources:
    image: registry.changhong.io/hlj/rcg-resources-server:dev
    restart: always
    volumes:
      - './upload/:/var/www/html/upload'
      - './src/:/var/www/html'
    expose:
      - 80
    ports:
      - 9000:80